-- BANCO DE DADOS AUTORECICLA

CREATE TABLE FILIAL(
	ID_FILIAL INT NOT NULL,
	NOME_UNIDADE VARCHAR(50) NOT NULL,
	CIDADE VARCVHAR(50) NOT NULL,
	CNPJ VARCHAR(14) NOT NULL
	CONSTRAINT PRIFILIAL PRIMARY KEY (ID_FILIAL)
);

CREATE TABLE VENDEDOR(
	ID_VENDEDOR INT NOT NULL,
	NOME VARCHAR(120) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	ID_FILIAL INT NOT NULL,
	CONSTRAINT PRIVENDEDOR PRIMARY KEY (ID_VENDEDOR),
	CONSTRAINT ESTFILIAL FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL
);

CREATE TABLE CLIENTE(
	ID_CLIENTE INT NOT NULL,
	NOME VARCHAR(120) NOT NULL,
	CPF_CNPJ VARCHAR(11) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	CONSTRAINT PRICLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE MARCA(
	ID_MARCA INT NOT NULL,
	NOME_MARCA VARCHAR(20) NOT NULL,
	CONSTRAINT PRIMARCA PRIMARY KEY (ID_MARCA)
);

CREATE TABLE MODELO(
	ID_MODELO INT NOT NULL,
	NOME_MODELO VARCHAR(20) NOT NULL,
	CONSTRAINT PRIMODELO PRIMARY KEY (ID_MODELO)
);

CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT NOT NULL,
	NOME_CATEGORIA VARCHAR(20) NOT NULL,
	CONSTRAINT PRICATEGORIA PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE PECA(
	ID_PECA INT NOT NULL,
	NOME_PECA VARCHAR(20) NOT NULL,
	VALOR DECIMAL NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	ID_FILIAL INT NOT NULL,
	CONSTRAINT PRIPECA PRIMARY KEY (ID_PECA),
	CONSTRAINT ESTCATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA,
	CONSTRAINT ESTPECAFILIAL FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL
);

CREATE TABLE COMPATIBILIDADE(
	ID_COMP INT NOT NULL,
	ID_PECA INT NOT NULL,
	ID_MODELO INT NOT NULL,
	ANO_INICIO DATE NOT NULL,
	ANO FIM DATE NOT NULL,
	CONSTRAINT PRICOMP PRIMARY KEY (ID_COMP),
	CONSTRAINT ESTPECA FOREIGN KEY (ID_PECA) REFERENCES PECA,
	CONSTRAINT ESTMODELO FOREIGN KEY (ID_MODELO) REFERENCES MODELO
);

CREATE TABLE NOTA(
	ID_NOTA INT NOT NULL,
	DATA_CRIACAO DATE NOT NULL,
	DATA_VENDA DATE NULL,
	STATUS VARCHAR(20) NOT NULL,
	FORMA_PAGAMENTO VARCHAR(20) NULL,
	VALOR_TOTAL DECIMAL NULL,
	ID_CLIENTE INT NOT NULL,
	ID_VENDEDOR INT NOT NULL,
	CONSTRAINT PRINOTA PRIMARY KEY (ID_NOTA),
	CONSTRAINT ESTCLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE,
	CONSTRAINT ESTVENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDENDOR
);

CREATE TABLE NOTA_PECA(
	ID_NOTA INT NOT NULL,
	ID_PECA INT NOT NULL,
	VALOR_VENDIDO DECIMAL NOT NULL,
	CONSTRAINT ESTNOTA FOREIGN KEY (ID_NOTA) REFERENCES NOTA,
	CONSTRAINT ESTPECA FOREIGN KEY (ID_PECA) REFERENCES PECA
);